// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJk-HYFxhBRmjw3ztqYUEe_vFv_1gbtw',
    appId: '1:66867873760:web:cfa2d3869bc341cd318d85',
    messagingSenderId: '66867873760',
    projectId: 'travel-catalog',
    authDomain: 'travel-catalog.firebaseapp.com',
    storageBucket: 'travel-catalog.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKMq4LTT8YpFDlAqC1OdUZjvJ3dhtjTxA',
    appId: '1:66867873760:android:c620a7b863a25521318d85',
    messagingSenderId: '66867873760',
    projectId: 'travel-catalog',
    storageBucket: 'travel-catalog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOnu2QEoA2vxdOEGXBfdhTRmoyNSA82r8',
    appId: '1:66867873760:ios:21a50fe3358cde07318d85',
    messagingSenderId: '66867873760',
    projectId: 'travel-catalog',
    storageBucket: 'travel-catalog.appspot.com',
    iosClientId:
        '66867873760-a0d4rcusdo88coamkdbeebpjvhsojuih.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelCatalog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOnu2QEoA2vxdOEGXBfdhTRmoyNSA82r8',
    appId: '1:66867873760:ios:21a50fe3358cde07318d85',
    messagingSenderId: '66867873760',
    projectId: 'travel-catalog',
    storageBucket: 'travel-catalog.appspot.com',
    iosClientId:
        '66867873760-a0d4rcusdo88coamkdbeebpjvhsojuih.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelCatalog',
  );
}
